#pragma once
/* 配网页面。单文件无外链——手机连的是没有互联网的热点，任何外部资源都加载不出来。
 * 移动优先：安全区适配、44px 触摸目标、长列表独立滚动、底部操作栏常驻。 */
static const char PORTAL_HTML[] =
"<!DOCTYPE html><html lang=zh><head><meta charset=utf-8>"
"<meta name=viewport content='width=device-width,initial-scale=1,viewport-fit=cover'>"
"<meta name=color-scheme content='dark light'>"
"<title>StickBox 配网</title><style>"
":root{--bg:#111418;--card:#1a1f25;--card2:#1e2329;--line:#2c3238;--fg:#e8eaed;--dim:#9aa0a6;--accent:#3b82f6}"
"@media(prefers-color-scheme:light){:root{--bg:#f5f6f8;--card:#fff;--card2:#eceef1;"
"--line:#d8dbe0;--fg:#1a1d21;--dim:#5f6470}}"
"*{box-sizing:border-box;-webkit-tap-highlight-color:transparent}"
"html{-webkit-text-size-adjust:100%}"
"body{margin:0;background:var(--bg);color:var(--fg);"
"font:16px/1.5 -apple-system,BlinkMacSystemFont,'PingFang SC','Noto Sans SC',sans-serif;"
"display:flex;flex-direction:column;min-height:100svh;"
"padding:env(safe-area-inset-top) env(safe-area-inset-right) 0 env(safe-area-inset-left)}"
"header,main,footer{width:100%;max-width:560px;margin:0 auto;padding:0 16px}"
"header{padding-top:20px;flex:none}"
"h1{font-size:21px;margin:0 0 4px;letter-spacing:-.01em}"
".sub{color:var(--dim);font-size:14px;margin-bottom:16px}"
"main{flex:1 1 auto;min-height:0;display:flex;flex-direction:column}"
"footer{flex:none;padding-bottom:calc(16px + env(safe-area-inset-bottom));"
"background:linear-gradient(transparent,var(--bg) 24px);padding-top:8px}"
"button{width:100%;min-height:48px;padding:13px;border:0;border-radius:12px;"
"background:var(--accent);color:#fff;font-size:16px;font-weight:600;font-family:inherit;cursor:pointer}"
"button:active{opacity:.7}button:disabled{background:var(--card2);color:var(--dim)}"
".ghost{background:var(--card2);color:var(--fg);margin-bottom:12px;font-weight:500}"
"ul{list-style:none;padding:0;margin:0 0 12px;overflow-y:auto;flex:1 1 auto;min-height:88px;"
"-webkit-overflow-scrolling:touch;overscroll-behavior:contain}"
"li{min-height:52px;padding:13px 14px;background:var(--card);border-radius:12px;margin-bottom:8px;"
"cursor:pointer;display:flex;justify-content:space-between;align-items:center;gap:12px}"
"li.sel{background:color-mix(in srgb,var(--accent) 22%,var(--card));"
"outline:2px solid var(--accent);outline-offset:-2px}"
".nm{font-weight:500;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;min-width:0}"
".rs{color:var(--dim);font-size:13px;white-space:nowrap;flex:none;font-variant-numeric:tabular-nums}"
"input{width:100%;min-height:48px;padding:13px;border:1px solid var(--line);border-radius:12px;"
"background:var(--card);color:var(--fg);font-size:16px;font-family:inherit;margin-bottom:10px}"
"input:focus{outline:2px solid var(--accent);outline-offset:-1px;border-color:transparent}"
"#msg{padding:13px 14px;border-radius:12px;margin-bottom:12px;display:none;font-size:15px}"
".ok{background:#14532d;color:#bbf7d0}.err{background:#5f1e1e;color:#fecaca}"
".info{background:#1e3a5f;color:#bfdbfe}"
".hint{color:var(--dim);font-size:12.5px;margin-top:10px;text-align:center;line-height:1.45}"
"@media(max-height:520px){header{padding-top:10px}h1{font-size:18px}.sub{margin-bottom:10px}"
".hint{display:none}}"
"</style></head><body>"
"<header><h1>StickBox 配网</h1>"
"<div class=sub>选择你的 Wi-Fi 并填入密码，再粘贴设备密钥。仅支持 2.4GHz 频段。</div>"
"<div id=msg></div>"
"<button class=ghost id=rescan onclick=scan()>重新扫描</button></header>"
"<main><ul id=list><li><span class=nm>扫描中…</span></li></ul></main>"
"<footer><input id=pw type=password placeholder='Wi-Fi 密码' autocomplete=off autocapitalize=off "
"autocorrect=off spellcheck=false>"
"<input id=dk placeholder='设备密钥（形如 a3f9….kJ8x…）' autocomplete=off autocapitalize=off "
"autocorrect=off spellcheck=false>"
"<button id=go onclick=go() disabled>连接</button>"
"<div class=hint>设备密钥由服务端签发，留空则沿用已保存的。<br>"
"连接测试时热点可能短暂断开，属正常现象。页面无响应时，请重连热点后刷新。</div>"
"</footer><script>"
"var sel='';"
"function m(t,c){var e=document.getElementById('msg');e.textContent=t;e.className=c;e.style.display='block'}"
"function esc(s){return s.replace(/[&<>\"]/g,function(c){"
"return{'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]})}"
"function scan(){"
" var b=document.getElementById('rescan');b.disabled=true;b.textContent='扫描中…';"
" document.getElementById('list').innerHTML='<li><span class=nm>扫描中…</span></li>';"
" fetch('/scan').then(r=>r.json()).then(function(d){"
"  var ul=document.getElementById('list');ul.innerHTML='';"
"  if(!d.length){ul.innerHTML='<li><span class=nm>没扫到网络，请重试</span></li>'}"
"  d.forEach(function(a){"
"   var li=document.createElement('li');"
"   li.innerHTML='<span class=nm>'+esc(a.s)+'</span><span class=rs>'+a.r+' dBm'+(a.k?' 🔒':'')+'</span>';"
"   li.onclick=function(){pick(li,a.s)};ul.appendChild(li)});"
"  b.disabled=false;b.textContent='重新扫描';"
" }).catch(function(){m('扫描失败，请重试','err');b.disabled=false;b.textContent='重新扫描'})}"
"function pick(el,s){sel=s;"
" [].forEach.call(document.querySelectorAll('#list li'),function(x){x.className=''});"
" el.className='sel';document.getElementById('go').disabled=false}"
"function go(){"
" if(!sel){m('请先选择一个网络','err');return}"
" document.getElementById('go').disabled=true;m('正在连接并验证密码…','info');"
" fetch('/connect',{method:'POST',headers:{'Content-Type':'application/json'},"
"  body:JSON.stringify({s:sel,p:document.getElementById('pw').value,"
"   k:document.getElementById('dk').value.trim()})})"
"  .then(function(){poll(0)}).catch(function(){poll(0)})}"
"function poll(n){"
" if(n>45){m('超时，请重连热点后重试','err');document.getElementById('go').disabled=false;return}"
" setTimeout(function(){"
"  fetch('/status').then(r=>r.json()).then(function(d){"
"   if(d.st==1){m('连接成功！IP '+d.ip+'　设备即将重启接入网络，热点将关闭。','ok')}"
"   else if(d.st==2){m('连接失败：'+d.e+'　请检查密码，或确认是 2.4GHz 网络','err');"
"    document.getElementById('go').disabled=false}"
"   else{poll(n+1)}"
"  }).catch(function(){poll(n+1)})},1000)}"
"scan();"
"</script></body></html>";
